---
title: "Fishery Advice - Celtic Seas"
author: "Prepared by: Scott I. Large"
date: "31 March 2016"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github("ICES-dk/rICES", force = FALSE)
# devtools::install_github("hadley/readxl", force = FALSE)
library(rICES)
library(readxl)
library(dplyr)
library(RColorBrewer)
library(knitr)
library(XML)
library(stringr)
library(reshape2)
library(ggplot2)
#
# library(plyr)
# library(RColorBrewer)
# library(extrafont)

# 
plotDir = "output/"
options(scipen = 5)
# 
catchURL <- "http://ices.dk/marine-data/Documents/CatchStats/OfficialNominalCatches.zip"
effortURL <- "http://stecf.jrc.ec.europa.eu/documents/43805/870977/2014_STECF+14-20+-+Fishing+Effort+Regimes+data+tables.zip"
spURL <- "ftp://ftp.fao.org/FI/STAT/DATA/ASFIS_sp.zip"
# 
tmpFileCatch <- tempfile(fileext = ".zip")
tmpFileEffort <- tempfile(fileext = ".zip")
tmpFileSp <- tempfile(fileext = ".zip")
# 
download.file(catchURL, destfile = tmpFileCatch, mode = "wb", quiet = T)
download.file(effortURL, destfile = tmpFileEffort, mode = "wb", quiet = T)
download.file(spURL, destfile = tmpFileSp, mode = "wb", quiet = T)
# 
catchDat <- read.csv(unz(tmpFileCatch,
                         "ICESCatchDataset2006-2014.csv"),
                     stringsAsFactors = F, header = T, fill = TRUE)
# 
# 
effortDat <- read_excel(unzip(tmpFileEffort, 
                              files = "Electronic_appendices/Effort_trends_by_country.xlsx"),
                        sheet = "kWdays at sea")
# 
spList <- read.table(unz(tmpFileSp,
                         "ASFIS_sp_Feb_2015.txt"),
                     header = TRUE,
                     fill = TRUE,
                     stringsAsFactors = FALSE)
# FAO codes and ICES stock codes 
speciesID <- read.csv("~/rCode/Data/ICESspeciesID_v1.csv",
                      stringsAsFactors = FALSE)
# Fishery guilds by ICES stock code
fisheryGuild <- read.csv("~/git/ices-dk/rStockOverview/fisheryGuild.csv",
                         stringsAsFactors = FALSE)
fisheryGuild$speciesID <- toupper(gsub( "-.*$", "", fisheryGuild$Stock.code))
# 
fisheryGuild <- fisheryGuild %>%
  inner_join(speciesID, c("speciesID" = "oldCode")) 
# 
# spList <- read.csv("https://raw.githubusercontent.com/ICES-dk/FisheriesAdvice/master/keys-lists/species.list",
#                    stringsAsFactors = FALSE)
# 
# Might not be needed anymore
# guildList <- read.csv("https://raw.githubusercontent.com/ICES-dk/FisheriesAdvice/master/keys-lists/guild.list",
#                       stringsAsFactors = FALSE)
#  
# 
ecoAreaCatch <- toupper(c("27.7.a",
                          "27.7.b", 
                          "27.7.c.2", 
                          "27.7.e", 
                          "27.7.f", 
                          "27.7.g", 
                          "27.7.h",
                          "27.7.j.2", 
                          "27.7.k.2", 
                          "27.6.a",
                          "27.6.b.NK",
                          "27.6.b.2"))
# 
# https://datacollection.jrc.ec.europa.eu/c/document_library/get_file?uuid=62841ee4-dbbd-4628-a7a7-5036ce5d415b&groupId=10213
ecoAreaEffort <- c("6 EU", "7BCEFGHJK")
# 
guildList <- 
  catchDat %>%
  Filter(f = function(x)!all(is.na(x))) %>%
  filter(Area %in% ecoAreaCatch) %>%
  melt(id.vars = c("Species", "Area", "Units", "Country"),
                   variable.name = "YEAR",
                   value.name = "VALUE") %>%
  mutate(YEAR = as.numeric(gsub("X", "", YEAR))) %>%
  group_by(Species) %>%
  mutate(totalCatch = sum(VALUE, na.rm = TRUE)) %>%
  inner_join(spList, c("Species" = "X3A_CODE")) %>%
  full_join(fisheryGuild, c("Species" = "newCode")) %>%
  select(Species, totalCatch, Scientific_name, English_name, Family, Fisheries.Guild) %>%
  ungroup() %>%
  arrange(-totalCatch) %>%
  filter(is.na(Fisheries.Guild) &
         totalCatch > 0) %>%
  distinct(Scientific_name)
# 
write.csv(guildList, file = "~/git/ices-dk/FisheriesAdvice/keys-lists/CS_spGuildList.csv",
          row.names = FALSE)


```

```{r catchDat, include = FALSE}
catchDat <-
  catchDat %>%
  Filter(f = function(x)!all(is.na(x))) %>%
  filter(Area %in% ecoAreaCatch) %>%
  melt(id.vars = c("Species", "Area", "Units", "Country"),
                   variable.name = "YEAR",
                   value.name = "VALUE") %>%
  mutate(YEAR = as.numeric(gsub("X", "", YEAR)))




str(tt)
unique(tt$Scientific_name)
str(guildList)
tr <- guildList[!guildList$scientific.name %in% tt$Scientific_name,]
tv <- spList[!spList$X3A_CODE %in% catchDat$Species,]
# tv <- catchDat[!catchDat$Species %in% spList$X3A_CODE,]

guil <- data.frame(SCI = unique(tt$scientific_name))

#
catchCountry <- catchDat %>%
  group_by(YEAR, Country) %>%
  dplyr::summarize(countryCatch = sum(VALUE)) # %>% # Total annual catch
# Convert country codes to proper names
#



```

```{r figure1, echo = FALSE, include = TRUE}
catchPlot <- catchCountry %>%
  group_by(Country) %>%
  dplyr::summarize(countryTotal = sum(countryCatch)) %>% # Overall catch to order plot
  arrange(-countryTotal) %>%
  dplyr::mutate(RANK = min_rank(desc(countryTotal))) %>% 
  inner_join(catchCountry, c("Country" = "Country")) %>%
  dplyr::mutate(Country = replace(Country, RANK > 9, "OTHER")) %>%
  group_by(YEAR, Country) %>%
  dplyr::mutate(countryCatch = sum(countryCatch)) %>%
  distinct(YEAR, Country)
# 
catchPlot$Country <- factor(catchPlot$Country, levels = rev(unique(catchPlot$Country)))
myColors <- c("grey40", brewer.pal(length(unique(catchPlot$Country)) - 1, "Spectral"))
names(myColors) <- levels(catchPlot$Country)
#
ggplot(catchPlot, aes(x = YEAR, y = countryCatch)) +
  geom_area(aes(fill = Country, color = Country), alpha = .8, position = "stack") +
  scale_fill_manual(values = myColors) +
  scale_color_manual(values = myColors) +
  labs(x = "Year",
       y = "Nominal Catch (tonnes)") +
  theme_bw() 
# 
```


```{r effortDat, include = FALSE}
effortDat <-
# tt <- 
  effortDat %>%
  Filter(f = function(x)!all(is.na(x))) %>%
  filter(reg_area_cod %in% ecoAreaEffort) %>%
  melt(id.vars = c("annex", "reg_area_cod", "reg_gear_cod", "Specon_calc", "country", "vessel_length"), 
       variable.name = "YEAR",
       value.name = "VALUE") %>%
  mutate(YEAR = as.numeric(YEAR))
#
effortCountry <- effortDat %>%
  group_by(YEAR, country) %>%
  dplyr::summarize(countryEffort = sum(VALUE, na.rm = T)) # %>% # Total annual catch
# Convert country codes to proper names

```


```{r figure2, echo = FALSE, include = TRUE}
effortPlot <- effortCountry %>%
  group_by(country) %>%
  dplyr::summarize(countryTotal = sum(countryEffort)) %>% # Overall catch to order plot
  arrange(-countryTotal) %>%
  dplyr::mutate(RANK = min_rank(desc(countryTotal))) %>% 
  inner_join(effortCountry, c("country" = "country")) %>%
  dplyr::mutate(country = replace(country, RANK > 9, "OTHER")) %>%
  group_by(YEAR, country) %>%
  dplyr::mutate(countryEffort = sum(countryEffort)) %>%
  distinct(YEAR, country)
# 
effortPlot$country <- factor(effortPlot$country, levels = rev(unique(effortPlot$country)))
myColors <- c("grey40", brewer.pal(length(unique(effortPlot$country)) - 1, "Spectral"))
names(myColors) <- levels(effortPlot$country)
#
ggplot(effortPlot, aes(x = YEAR, y = countryEffort)) +
  geom_area(aes(fill = country, color = country), alpha = .8, position = "stack") +
  scale_fill_manual(values = myColors) +
  scale_color_manual(values = myColors) +
  labs(x = "Year",
       y = "Effort (kW days at sea)") +
  theme_bw() 
```

## Guild and ecoregion

The following stocks, guilds, and ecoregions have been included in the overview. F~MSY~ F, SSB, and MSY B~trigger~ were downloaded from [ICES Stock Assessment Graphs](http://ices.dk/marine-data/tools/Pages/stock-assessment-graphs.aspx). Click the links to see the [aggregated data](https://github.com/ICES-dk/rStockOverview/blob/master/NordicCouncilRefPoints.csv) and [R code](https://github.com/ICES-dk/rStockOverview/blob/master/nordicIndicators.rmd) used to download and plot  [Figure 1](https://github.com/ICES-dk/rStockOverview/blob/master/output/NordicCouncilRefPoints_ALL.png) and [Figure 2](https://github.com/ICES-dk/rStockOverview/blob/master/output/NordicCouncilRefPoints_ecoregion-guild.png).

For questions, please email <A HREF="mailto:scott.large@ices.dk?subject=Nordic Council plots">scott.large@ices.dk</A>.

<!-- ```{r guildlist, echo=FALSE, include=TRUE} -->
<!-- # -->
<!-- guildList <- read.csv("~/git/ices-dk/rStockOverview/fisheryGuild.csv") -->
<!-- # -->
<!-- guildList <- guildList %>% -->
<!--   rename(Stock = Stock.code, -->
<!--          GUILD = Fisheries.Guild) %>% -->
<!--   filter(GUILD %in% c("pelagic", "benthic", "demersal")) %>% -->
<!--   mutate(Stock = tolower(Stock), -->
<!--          Stock = gsub("[[:space:]]", "", Stock)) -->
<!-- # -->

<!-- overTable <- guildList %>% -->
<!--   inner_join(stockTable, c("Stock" = "STOCKID")) %>% -->
<!--   rename(ECOREGION = EcoRegion) %>% -->
<!--   distinct(ECOREGION, GUILD, Stock) %>% -->
<!--   select(ECOREGION, GUILD, Stock, FMSY, MSYBtrigger) %>% -->
<!--   filter(ECOREGION %in% c("North Sea", "Iceland and East Greenland", -->
<!--                           "Widely distributed and migratory stocks", -->
<!--                           "Baltic Sea", "Faroe Plateau Ecosystem", -->
<!--                           "Barents Sea and Norwegian Sea")) %>% -->
<!--   filter(!is.na(FMSY) | !is.na(MSYBtrigger)) %>% -->
<!--   arrange(ECOREGION, GUILD) -->
<!-- # -->
<!-- knitr::kable(overTable, format="markdown") -->
<!-- ``` -->


<!-- ```{r stocktable, echo = FALSE} -->
<!-- # -->
<!-- df <- guildList %>% -->
<!--   inner_join(stockTable, c("Stock" = "STOCKID")) %>% -->
<!--   rename(ECOREGION = EcoRegion) %>% -->
<!--   filter(SpeciesName != "Psetta maxima (historic name)" & -->
<!--            Stock %in% unique(guildList$Stock) & -->
<!--            ECOREGION %in% c("North Sea", "Iceland and East Greenland", -->
<!--                           "Widely distributed and migratory stocks", -->
<!--                           "Baltic Sea", "Faroe Plateau Ecosystem", -->
<!--                           "Barents Sea and Norwegian Sea")) %>% -->
<!--   mutate(fishingPressureDescription = gsub("Fishing Pressure: " , "", fishingPressureDescription), -->
<!--          fishingPressureDescription = gsub("Fishing pressure: " , "", fishingPressureDescription), -->
<!--          stockSizeDescription = ifelse(stockSizeDescription == "NA", "Stock Size: Relative", stockSizeDescription), -->
<!--          FmsyDescription = "FMSY", -->
<!--          stockSizeDescription = gsub("Stock Size: ", "", stockSizeDescription)) %>% -->
<!--   filter(stockSizeDescription != "B/BMSY" | -->
<!--            fishingPressureDescription != "F/FMSY") %>% -->
<!--   group_by(Stock) %>% -->
<!--   mutate(F_FMSY = F / FMSY, -->
<!--          SSB_MSYBtrigger = SSB / MSYBtrigger) %>% -->
<!--   melt(id.vars = c("AssessmentYear",  "ECOREGION", "GUILD","Stock", "Year"), -->
<!--        measure.vars = c("F_FMSY", "SSB_MSYBtrigger"), -->
<!--        variable.name = "METRIC", -->
<!--        value.name = "VALUE") %>% -->
<!--   rename(STOCKID = Stock, -->
<!--          YEAR = Year, -->
<!--          stockValue = VALUE) %>% -->
<!--   filter(!is.na(stockValue)) %>% # remove NA VALUE -->
<!--   group_by(ECOREGION, GUILD, METRIC, YEAR) %>% -->
<!--   mutate(ecoGuildMean = mean(stockValue)) %>% -->
<!--   group_by(ECOREGION, METRIC, YEAR) %>% -->
<!--   mutate(ecoValue = mean(stockValue)) %>% -->
<!--   group_by(METRIC, GUILD, YEAR) %>% -->
<!--   mutate(allMean = mean(stockValue)) -->

<!-- write.csv(df, file = "~/git/ices-dk/rStockOverview/NordicCouncilRefPoints.csv", -->
<!--           row.names = FALSE) -->
<!-- # -->
<!-- ``` -->

<!-- ## Figure 1. ## -->

<!-- F/F~MSY~ and SSB/MSY B~trigger~ averaged by guild for all ecoregions. [Link to .png](https://github.com/ICES-dk/rStockOverview/blob/master/output/NordicCouncilRefPoints_ALL.png) -->

<!-- ```{r echo = FALSE, include = TRUE} -->
<!-- df %>% -->
<!--   ungroup() %>% -->
<!--   distinct(GUILD, METRIC, YEAR) %>% -->
<!--   ggplot(aes(x = YEAR, y = allMean, col = GUILD)) + -->
<!--   geom_line() + -->
<!--   geom_hline(yintercept = 1, col = "grey40", linetype = "dashed") + -->
<!--   # scale_y_continuous(limits = c(0, 3.2)) + -->
<!--   scale_color_manual(values = c("#7fc97f","#ef3b2c","#662506")) + -->
<!--   facet_grid(~METRIC) + -->
<!--   theme_bw() + -->
<!--   theme(legend.position = "bottom", -->
<!--         strip.text = element_text(size = 12, angle = 0, hjust = 0), -->
<!--         strip.background = element_blank(), -->
<!--         legend.key = element_rect(colour = NA)) + -->
<!--   labs(x = "Year", y = "Metric") -->
<!-- ggsave(filename = paste0(plotDir, "NordicCouncilRefPoints_ALL.png"), width = 6.5, -->
<!--        height = 4.5) -->
<!-- ``` -->
<!-- \pagebreak -->

<!-- ## Figure 2. ## -->

<!-- F/F~MSY~ and SSB/MSY B~trigger~ averaged for each ecoregion and guild. [Link to .png](https://github.com/ICES-dk/rStockOverview/blob/master/output/NordicCouncilRefPoints_ecoregion-guild.png) -->

<!-- ```{r echo = FALSE, include = TRUE} -->

<!-- df %>% -->
<!--   mutate(ECOGUILD = paste0(ECOREGION,", ", GUILD)) %>% -->
<!--   ungroup() %>% -->
<!--   # select(ECOGUILD, METRIC, YEAR, ecoGuildMean) %>% -->
<!--   distinct(ECOGUILD, METRIC, YEAR) %>% -->
<!--   filter(YEAR >= 1990) %>% -->
<!--   ggplot(aes(x = YEAR, y = ecoGuildMean, col = METRIC)) + -->
<!--   geom_line() + -->
<!--   geom_hline(yintercept = 1, col = "grey40", linetype = "dashed") + -->
<!--   # scale_y_continuous(limits = c(0, 3.2)) + -->
<!--   facet_grid(GUILD ~ ECOREGION) + -->
<!--   scale_color_manual(values = c("#386cb0","#fdb462")) + -->
<!--   theme_bw() + -->
<!--   theme(legend.position = "bottom", -->
<!--         strip.text = element_text(size = 6, angle = 0, hjust = 0), -->
<!--         axis.text.x = element_text(size = 6, angle = 45), -->
<!--         strip.background = element_blank(), -->
<!--         legend.key = element_rect(colour = NA)) + -->
<!--   labs(x = "Year", y = "Metric") -->
<!-- ggsave(filename = paste0(plotDir, "NordicCouncilRefPoints_ecoregion-guild.png"), width = 6.5, -->
<!--        height = 4.5) -->

<!-- ``` -->
